#!/bin/bash
BASE="http://127.0.0.1:3001/api/v1/email"
TID="1f102ba0-b373-45c5-9aa5-5d5620c0b495"
echo "=== GET Template by ID ==="
curl -s "$BASE/templates/$TID"
echo ""
echo "=== PUT Update Template ==="
curl -s -X PUT "$BASE/templates/$TID" -H "Content-Type: application/json" -d "{\"name\":\"Updated Welcome\",\"subject\":\"Welcome Back!\",\"body\":\"<h1>Updated</h1>\",\"variables\":[\"name\"],\"category\":\"newsletter\"}"
echo ""
echo "=== Verify Update ==="
curl -s "$BASE/templates/$TID" | python3 -m json.tool
echo ""
echo "=== DELETE Template ==="
curl -s -X DELETE "$BASE/templates/$TID"
echo ""
echo "=== Verify Delete ==="
curl -s "$BASE/templates"
echo ""