#!/usr/bin/env bash
# Multi-Directory — buyer-side installer (kanban B85, handover readiness).
#
# Brings a freshly-cloned checkout onto the operator's OWN server and leaves it able to:
#   1. talk to a Postgres it controls,
#   2. build the full schema from nothing (the same migration path the app uses at boot),
#   3. create the first admin login (a fresh DB has NO user row — this is that door).
#
# It is deliberately boring and idempotent: re-running it changes nothing except what is missing.
#
#   sudo bash deploy/install.sh --database-url postgres://user:pass@127.0.0.1/db --admin-email you@example.com
#
# Nothing here reads or writes /opt/swift — this is the buyer's copy, standalone.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

DB_URL=""
BIN=""
BUILD=0
ADMIN_EMAIL=""
ADMIN_PASSWORD=""
PORT="8089"
BASE_DOMAIN="localhost"
UPLOADS_ROOT=""
ENV_FILE="$APP_DIR/.env"
FORCE_ENV=0
SYSTEMD=0
DRY_RUN=0
SERVICE_USER="$(id -un)"

usage() {
  sed -n '2,12p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
  cat <<EOF

OPTIONS
  --database-url URL     Postgres the directory will use (default: \$DATABASE_URL, else .env)
  --binary PATH          prebuilt ./target/release/multidirectory (default: auto-detect)
  --build                build the release binary with cargo first (needs a Rust toolchain)
  --admin-email EMAIL    create/replace the first admin login
  --admin-password PASS  pin the password (default: generated and printed once)
  --port N               HTTP port for the app (default: ${PORT})
  --base-domain NAME     BASE_DOMAIN value (default: ${BASE_DOMAIN})
  --uploads-root DIR     where uploaded files live (default: <app>/uploads)
  --env-file PATH        where to write the .env (default: ${APP_DIR}/.env)
  --force-env            overwrite an existing .env
  --systemd              also write + enable a systemd unit (Linux, root)
  --dry-run              print the plan, change nothing
  -h, --help             this text
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --database-url) DB_URL="${2:?}"; shift 2 ;;
    --binary) BIN="${2:?}"; shift 2 ;;
    --build) BUILD=1; shift ;;
    --admin-email) ADMIN_EMAIL="${2:?}"; shift 2 ;;
    --admin-password) ADMIN_PASSWORD="${2:?}"; shift 2 ;;
    --port) PORT="${2:?}"; shift 2 ;;
    --base-domain) BASE_DOMAIN="${2:?}"; shift 2 ;;
    --uploads-root) UPLOADS_ROOT="${2:?}"; shift 2 ;;
    --env-file) ENV_FILE="${2:?}"; shift 2 ;;
    --force-env) FORCE_ENV=1; shift ;;
    --systemd) SYSTEMD=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage; exit 2 ;;
  esac
done

say()  { printf '\033[1m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[33mwarn:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[31merror:\033[0m %s\n' "$*" >&2; exit 1; }

command -v psql >/dev/null 2>&1 || die "psql is required (apt-get install -y postgresql-client)"

# ── 1. database URL ─────────────────────────────────────────────────────────────────────────
if [ -z "$DB_URL" ]; then
  DB_URL="${DATABASE_URL:-}"
fi
if [ -z "$DB_URL" ] && [ -f "$ENV_FILE" ]; then
  DB_URL="$(grep -E '^DATABASE_URL=' "$ENV_FILE" | head -1 | cut -d= -f2- || true)"
fi
[ -n "$DB_URL" ] || die "no database: pass --database-url or set DATABASE_URL"

say "checking the database is reachable"
psql "$DB_URL" -Atc 'SELECT 1' >/dev/null || die "cannot connect to the database"

# ── 2. binary ───────────────────────────────────────────────────────────────────────────────
if [ -z "$BIN" ]; then
  BIN="$APP_DIR/target/release/multidirectory"
fi
if [ "$BUILD" = "1" ]; then
  command -v cargo >/dev/null 2>&1 || die "--build needs cargo (rustup.rs)"
  say "building the release binary (this takes a few minutes)"
  [ "$DRY_RUN" = "1" ] || (cd "$APP_DIR" && cargo build --release --bin multidirectory)
fi
[ "$DRY_RUN" = "1" ] || [ -x "$BIN" ] || die "no executable at $BIN — build it (--build) or pass --binary"

# ── 3. .env ─────────────────────────────────────────────────────────────────────────────────
if [ -f "$ENV_FILE" ] && [ "$FORCE_ENV" != "1" ]; then
  warn "$ENV_FILE already exists — left untouched (use --force-env to rewrite)"
else
  say "writing $ENV_FILE"
  if [ "$DRY_RUN" != "1" ]; then
    umask 077
    [ -n "$UPLOADS_ROOT" ] || UPLOADS_ROOT="$APP_DIR/uploads"
    mkdir -p "$(dirname "$ENV_FILE")" "$UPLOADS_ROOT"
    cat > "$ENV_FILE" <<EOF
# Multi-Directory — generated by deploy/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Secrets below are random and unique to this install. Keep this file 0600.
DATABASE_URL=$DB_URL
JWT_SECRET=$(openssl rand -hex 32)
PROVIDER_KEY_ENC_SECRET=$(openssl rand -hex 24)
APP_HOST=127.0.0.1
APP_PORT=$PORT
BASE_DOMAIN=$BASE_DOMAIN
MD_UPLOADS_ROOT=$UPLOADS_ROOT
RUST_LOG=info
EOF
  fi
fi

# ── 4. schema ───────────────────────────────────────────────────────────────────────────────
say "applying the schema from nothing (src/migrations)"
if [ "$DRY_RUN" = "1" ]; then
  echo "    dry-run: $BIN migrate"
else
  (cd "$APP_DIR" && "$BIN" migrate --database-url "$DB_URL")
fi

# ── 5. first admin ──────────────────────────────────────────────────────────────────────────
if [ -n "$ADMIN_EMAIL" ]; then
  say "creating the first admin login: $ADMIN_EMAIL"
  if [ "$DRY_RUN" = "1" ]; then
    echo "    dry-run: $BIN create-admin --email $ADMIN_EMAIL"
  else
    args=(create-admin --email "$ADMIN_EMAIL" --database-url "$DB_URL")
    [ -n "$ADMIN_PASSWORD" ] && args+=(--password "$ADMIN_PASSWORD")
    (cd "$APP_DIR" && "$BIN" "${args[@]}")
  fi
else
  warn "no --admin-email: the database has NO login row yet. Create one with:"
  echo "    $BIN create-admin --email you@example.com"
fi

# ── 6. systemd (optional) ───────────────────────────────────────────────────────────────────
if [ "$SYSTEMD" = "1" ]; then
  UNIT=/etc/systemd/system/multidirectory.service
  say "writing $UNIT"
  if [ "$DRY_RUN" != "1" ]; then
    [ "$(id -u)" = "0" ] || die "--systemd needs root"
    cat > "$UNIT" <<EOF
[Unit]
Description=Multi-Directory
After=network-online.target postgresql.service
Wants=network-online.target

[Service]
Type=simple
User=$SERVICE_USER
WorkingDirectory=$APP_DIR
EnvironmentFile=$ENV_FILE
ExecStart=$BIN
Restart=always
RestartSec=3
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    systemctl enable --now multidirectory
  fi
fi

say "done"
cat <<EOF

Next:
  * start it:   cd $APP_DIR && set -a && . $ENV_FILE && set +a && $BIN
    (or --systemd to run it as a service)
  * health:     curl -sf http://127.0.0.1:$PORT/api/v1/health
  * admin:      http://127.0.0.1:$PORT/admin-panel.html  (log in with the admin you just made)
  * upgrades:   bash deploy/upgrade.sh
  * read:       HOSTING.md
EOF
