//! Nightly sitemap regeneration + search-engine submission (B91 / B117 gap #10,
//! B142).
//!
//! The SEO engine *serves* sitemaps but nothing ever told a search engine that
//! content changed, and nothing regenerated on a schedule. This module adds the
//! missing submission loop behind the admin panel:
//!
//!   * ONE editable settings row (`seo_submission_settings`, migration 144) —
//!     `is_enabled`, `cadence_hours`, an optional `sitemap_url` override and a
//!     `ping_targets` JSON array of `{name,url,enabled}`. Nothing is hardwired:
//!     any endpoint can be added/replaced from the panel.
//!   * `{sitemap}` in a target URL is substituted with the URL-encoded sitemap
//!     URL; `{sitemap_raw}` with the raw URL.
//!   * an IndexNow leg (migration 150). The legacy Google/Bing `?sitemap=` ping
//!     endpoints were RETIRED — measured 2026-10-08: Google answers 404
//!     ("Sitemaps ping is deprecated") and Bing answers 410 Gone. The live
//!     replacement is IndexNow: when `indexnow_key` is set the run POSTs the
//!     sitemap's URLs to `https://api.indexnow.org/indexnow` with the key, and
//!     the key is served back from `/indexnow-key.txt` at the host ROOT so the
//!     engine can verify ownership (IndexNow refuses a nested keyLocation path).
//!   * a background task checks every 5 minutes for a due global row and runs it;
//!     the same run is available on demand (`POST /seo/run-submission`) and each
//!     target hit is written to `seo_submission_log` (status + ok + detail) so the
//!     panel can show what the engine actually answered.
//!
//! A disabled row is never touched, an unconfigured row records `nothing_enabled`
//! instead of faking success, and no failure panics the scheduler.

use axum::{
    extract::State,
    http::{header, StatusCode},
    response::IntoResponse,
    Extension, Json,
};
use chrono::{DateTime, Duration, Utc};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use sqlx::PgPool;
use uuid::Uuid;

use crate::auth::middleware::is_super_admin;
use crate::auth::models::Claims;
use crate::error::{ApiResult, AppError};
use crate::AppState;

/// Seeded the first time the panel (or the scheduler) reads an unconfigured row.
/// The old Google/Bing `?sitemap=` ping endpoints are RETIRED (Google 404, Bing
/// 410), so nothing is seeded by default — the live submission leg today is
/// IndexNow (see `indexnow_key`), and an admin may still add any GET endpoint
/// here (an IndexNow consumer, a Baidu ping, anything).
const DEFAULT_TARGETS: &str = "[]";

/// IndexNow accepts up to 10 000 urls per request; we cap so an unexpectedly
/// huge sitemap cannot build an unbounded body.
const INDEXNOW_MAX_URLS: usize = 10_000;

fn default_enabled() -> bool {
    true
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PingTarget {
    pub name: String,
    pub url: String,
    #[serde(default = "default_enabled")]
    pub enabled: bool,
}

#[derive(Debug, Serialize, Deserialize, sqlx::FromRow)]
pub struct SubmissionSettings {
    pub id: Uuid,
    pub directory_id: Option<Uuid>,
    pub is_enabled: bool,
    pub cadence_hours: i32,
    pub sitemap_url: Option<String>,
    pub ping_targets: Value,
    pub indexnow_key: Option<String>,
    pub last_run_at: Option<DateTime<Utc>>,
    pub last_status: Option<String>,
    pub next_run_at: Option<DateTime<Utc>>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Deserialize)]
pub struct UpdateSubmissionRequest {
    pub is_enabled: Option<bool>,
    pub cadence_hours: Option<i32>,
    pub sitemap_url: Option<String>,
    pub ping_targets: Option<Vec<PingTarget>>,
    #[serde(default)]
    pub indexnow_key: Option<String>,
}

// ── helpers ─────────────────────────────────────────────────────────────────

/// Percent-encode a value for use inside a query string. Only the unreserved
/// set survives; everything else (the `:` and `/` of a URL) becomes `%XX`.
fn encode_component(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for b in s.bytes() {
        match b {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                out.push(b as char)
            }
            _ => out.push_str(&format!("%{:02X}", b)),
        }
    }
    out
}

fn resolve_sitemap(override_url: Option<&str>, base_domain: &str) -> String {
    match override_url {
        Some(u) if !u.trim().is_empty() => u.trim().to_string(),
        _ => format!("https://{}/sitemap.xml", base_domain.trim_end_matches('/')),
    }
}

/// Every `<loc>…</loc>` value in a sitemap, de-duplicated and order-preserving.
/// Deliberately a string scan (no XML dependency): the sitemap is generated by
/// this same service and only ever contains `<loc>` text.
fn parse_locs(xml: &str) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    let mut rest = xml;
    while let Some(i) = rest.find("<loc>") {
        let after = &rest[i + 5..];
        match after.find("</loc>") {
            Some(j) => {
                let loc = after[..j].trim();
                if !loc.is_empty() && !out.iter().any(|e| e == loc) {
                    out.push(loc.to_string());
                }
                rest = &after[j + 6..];
            }
            None => break,
        }
    }
    out
}

/// `https://host[[:port]]` from an absolute URL (no path).
fn origin_of(url: &str) -> Option<String> {
    let scheme_end = url.find("://")?;
    let scheme = &url[..scheme_end];
    let rest = &url[scheme_end + 3..];
    let end = rest.find('/').unwrap_or(rest.len());
    let authority = &rest[..end];
    if authority.is_empty() {
        return None;
    }
    Some(format!("{scheme}://{authority}"))
}

/// Fetch the sitemap, take its URLs, and submit them to IndexNow.
/// Returns `(status_code, ok, detail, url_count)` — never panics on a bad engine
/// answer, so a submission failure is recorded rather than propagated.
async fn submit_indexnow(
    client: &reqwest::Client,
    sitemap_url: &str,
    key: &str,
) -> (Option<i32>, bool, Option<String>, usize) {
    let xml = match client.get(sitemap_url).send().await {
        Ok(r) if r.status().is_success() => match r.text().await {
            Ok(t) => t,
            Err(e) => return (None, false, Some(format!("sitemap read: {e}")), 0),
        },
        Ok(r) => {
            return (
                None,
                false,
                Some(format!("sitemap HTTP {}", r.status().as_u16())),
                0,
            )
        }
        Err(e) => return (None, false, Some(format!("sitemap fetch: {e}")), 0),
    };

    let mut locs = parse_locs(&xml);
    // The key file must live on the same host as the submitted urls, so derive the
    // host from the sitemap itself rather than a hardcoded domain. IndexNow wants
    // `host` WITHOUT a scheme; `keyLocation` is the full absolute URL.
    let origin = match locs.first().and_then(|u| origin_of(u)) {
        Some(h) => h,
        None => {
            return (
                None,
                false,
                Some("sitemap had no absolute <loc>".to_string()),
                0,
            )
        }
    };
    let host = origin
        .split("://")
        .nth(1)
        .unwrap_or(origin.as_str())
        .to_string();
    if locs.len() > INDEXNOW_MAX_URLS {
        locs.truncate(INDEXNOW_MAX_URLS);
    }
    let n = locs.len();

    let body = json!({
        "host": host,
        "key": key,
        "keyLocation": format!("{origin}/indexnow-key.txt"),
        "urlList": locs,
    });

    match client
        .post("https://api.indexnow.org/indexnow")
        .header("content-type", "application/json; charset=utf-8")
        .json(&body)
        .send()
        .await
    {
        Ok(resp) => {
            let code = resp.status().as_u16() as i32;
            let ok = resp.status().is_success();
            let detail = if ok {
                None
            } else {
                let text = resp.text().await.unwrap_or_default();
                Some(format!(
                    "HTTP {code} {}",
                    text.chars().take(120).collect::<String>()
                ))
            };
            (Some(code), ok, detail, n)
        }
        Err(e) => (None, false, Some(format!("indexnow post: {e}")), n),
    }
}

/// Read the platform-wide row, creating it (disabled, with default targets) if it
/// does not exist yet. `ON CONFLICT DO NOTHING` keeps a concurrent boot safe.
async fn ensure_global_row(db: &PgPool) -> Result<SubmissionSettings, AppError> {
    if let Some(row) = sqlx::query_as::<_, SubmissionSettings>(
        "SELECT * FROM seo_submission_settings WHERE directory_id IS NULL \
         ORDER BY updated_at DESC LIMIT 1",
    )
    .fetch_optional(db)
    .await?
    {
        return Ok(row);
    }

    let defaults: Value = serde_json::from_str(DEFAULT_TARGETS).unwrap_or_else(|_| json!([]));
    let inserted = sqlx::query_as::<_, SubmissionSettings>(
        "INSERT INTO seo_submission_settings (directory_id, is_enabled, cadence_hours, ping_targets) \
         VALUES (NULL, false, 24, $1) ON CONFLICT DO NOTHING RETURNING *",
    )
    .bind(&defaults)
    .fetch_optional(db)
    .await?;

    match inserted {
        Some(row) => Ok(row),
        None => Ok(sqlx::query_as::<_, SubmissionSettings>(
            "SELECT * FROM seo_submission_settings WHERE directory_id IS NULL \
             ORDER BY updated_at DESC LIMIT 1",
        )
        .fetch_one(db)
        .await?),
    }
}

/// Run one submission pass for a settings row: hit every enabled GET target,
/// then the IndexNow leg when a key is configured; log each result, then stamp
/// last_run_at / last_status / next_run_at. Never returns an error for a target
/// that failed — those are recorded, not propagated.
pub async fn run_submission(
    db: &PgPool,
    row: &SubmissionSettings,
    base_domain: &str,
) -> Result<Value, AppError> {
    let sitemap = resolve_sitemap(row.sitemap_url.as_deref(), base_domain);
    let encoded = encode_component(&sitemap);
    let targets: Vec<PingTarget> =
        serde_json::from_value(row.ping_targets.clone()).unwrap_or_default();

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(20))
        .user_agent("Mozilla/5.0 (compatible; SwiftOps/1.0)")
        .build()
        .map_err(|e| AppError::Internal(format!("http client: {e}")))?;

    let mut results = Vec::new();
    let mut any_ok = false;
    let mut enabled_count = 0usize;

    for t in targets.iter().filter(|t| t.enabled) {
        enabled_count += 1;
        let url = t
            .url
            .replace("{sitemap}", &encoded)
            .replace("{sitemap_raw}", &sitemap);

        let (status_code, ok, detail) = match client.get(&url).send().await {
            Ok(resp) => {
                let code = resp.status().as_u16() as i32;
                let ok = resp.status().is_success();
                (
                    Some(code),
                    ok,
                    if ok {
                        None
                    } else {
                        Some(format!("HTTP {code}"))
                    },
                )
            }
            Err(e) => (None, false, Some(e.to_string())),
        };
        any_ok = any_ok || ok;

        sqlx::query(
            "INSERT INTO seo_submission_log \
             (directory_id, target_name, endpoint_url, sitemap_url, status_code, ok, detail) \
             VALUES ($1,$2,$3,$4,$5,$6,$7)",
        )
        .bind(row.directory_id)
        .bind(&t.name)
        .bind(&url)
        .bind(&sitemap)
        .bind(status_code)
        .bind(ok)
        .bind(&detail)
        .execute(db)
        .await?;

        results.push(json!({
            "target": t.name,
            "url": url,
            "status_code": status_code,
            "ok": ok,
            "detail": detail,
        }));
    }

    // ── IndexNow leg — the live 2026 replacement for the retired Google/Bing pings.
    if let Some(key) = row
        .indexnow_key
        .as_deref()
        .map(str::trim)
        .filter(|k| !k.is_empty())
    {
        enabled_count += 1;
        let (status_code, ok, detail, url_count) = submit_indexnow(&client, &sitemap, key).await;
        any_ok = any_ok || ok;

        sqlx::query(
            "INSERT INTO seo_submission_log \
             (directory_id, target_name, endpoint_url, sitemap_url, status_code, ok, detail) \
             VALUES ($1,$2,$3,$4,$5,$6,$7)",
        )
        .bind(row.directory_id)
        .bind("IndexNow")
        .bind("https://api.indexnow.org/indexnow")
        .bind(&sitemap)
        .bind(status_code)
        .bind(ok)
        .bind(&detail)
        .execute(db)
        .await?;

        results.push(json!({
            "target": "IndexNow",
            "url": "https://api.indexnow.org/indexnow",
            "status_code": status_code,
            "ok": ok,
            "detail": detail,
            "urls_submitted": url_count,
        }));
    }

    let status = if enabled_count == 0 {
        "nothing_enabled"
    } else if any_ok {
        "ok"
    } else {
        "failed"
    };
    let next = Utc::now() + Duration::hours(i64::from(row.cadence_hours.max(1)));
    sqlx::query(
        "UPDATE seo_submission_settings \
         SET last_run_at = now(), last_status = $1, next_run_at = $2, updated_at = now() \
         WHERE id = $3",
    )
    .bind(status)
    .bind(next)
    .bind(row.id)
    .execute(db)
    .await?;

    Ok(json!({
        "status": status,
        "sitemap_url": sitemap,
        "targets_submitted": enabled_count,
        "results": results,
    }))
}

// ── HTTP surface ────────────────────────────────────────────────────────────

/// GET /api/v1/seo/submission-settings
pub async fn get_settings(
    State(s): State<AppState>,
    Extension(claims): Extension<Claims>,
) -> ApiResult<impl IntoResponse> {
    if !is_super_admin(&claims) {
        return Err(AppError::Forbidden(
            "Admin role required to view sitemap submission settings".to_string(),
        ));
    }

    let row = ensure_global_row(&s.db).await?;
    let resolved = resolve_sitemap(row.sitemap_url.as_deref(), &s.config.base_domain);

    let recent = sqlx::query_as::<_, (DateTime<Utc>, String, String, Option<i32>, bool)>(
        "SELECT created_at, target_name, endpoint_url, status_code, ok \
         FROM seo_submission_log ORDER BY created_at DESC LIMIT 20",
    )
    .fetch_all(&s.db)
    .await?;

    Ok(Json(json!({
        "settings": row,
        "resolved_sitemap_url": resolved,
        "recent": recent
            .into_iter()
            .map(|(at, target, endpoint, code, ok)| json!({
                "at": at, "target": target, "endpoint": endpoint,
                "status_code": code, "ok": ok,
            }))
            .collect::<Vec<_>>(),
    })))
}

/// PUT /api/v1/seo/submission-settings
pub async fn update_settings(
    State(s): State<AppState>,
    Extension(claims): Extension<Claims>,
    Json(body): Json<UpdateSubmissionRequest>,
) -> ApiResult<impl IntoResponse> {
    if !is_super_admin(&claims) {
        return Err(AppError::Forbidden(
            "Admin role required to edit sitemap submission settings".to_string(),
        ));
    }

    let current = ensure_global_row(&s.db).await?;
    let is_enabled = body.is_enabled.unwrap_or(current.is_enabled);
    let cadence = body.cadence_hours.unwrap_or(current.cadence_hours).max(1);
    let sitemap = body.sitemap_url.or_else(|| current.sitemap_url.clone());
    let targets = match body.ping_targets {
        Some(t) => serde_json::to_value(t).unwrap_or_else(|_| json!([])),
        None => current.ping_targets.clone(),
    };
    // An explicit (possibly empty) key replaces; an absent field keeps the row.
    // An empty string disables the IndexNow leg without losing the target list.
    let indexnow = match body.indexnow_key {
        Some(k) => {
            let k = k.trim().to_string();
            if k.is_empty() {
                None
            } else {
                Some(k)
            }
        }
        None => current.indexnow_key.clone(),
    };

    let row = sqlx::query_as::<_, SubmissionSettings>(
        "UPDATE seo_submission_settings \
         SET is_enabled = $1, cadence_hours = $2, sitemap_url = $3, ping_targets = $4, \
             indexnow_key = $5, updated_at = now() \
         WHERE id = $6 RETURNING *",
    )
    .bind(is_enabled)
    .bind(cadence)
    .bind(&sitemap)
    .bind(&targets)
    .bind(&indexnow)
    .bind(current.id)
    .fetch_one(&s.db)
    .await?;

    Ok(Json(json!({ "settings": row })))
}

/// POST /api/v1/seo/run-submission — run the submission pass now.
pub async fn run_now(
    State(s): State<AppState>,
    Extension(claims): Extension<Claims>,
) -> ApiResult<impl IntoResponse> {
    if !is_super_admin(&claims) {
        return Err(AppError::Forbidden(
            "Admin role required to run sitemap submission".to_string(),
        ));
    }

    let row = ensure_global_row(&s.db).await?;
    let outcome = run_submission(&s.db, &row, &s.config.base_domain).await?;
    Ok(Json(outcome))
}

/// GET /indexnow-key.txt — PUBLIC (no credential), served at the host ROOT.
/// IndexNow re-fetches this to verify ownership before it trusts a submission and
/// refuses a nested keyLocation path (HTTP 422), so it must live at `/`. 404 when
/// no key is configured, so an unset platform never serves a stray file.
pub async fn indexnow_key_file(State(s): State<AppState>) -> impl IntoResponse {
    let key = sqlx::query_scalar::<_, Option<String>>(
        "SELECT indexnow_key FROM seo_submission_settings \
         WHERE directory_id IS NULL LIMIT 1",
    )
    .fetch_optional(&s.db)
    .await
    .ok()
    .flatten()
    .flatten()
    .map(|k| k.trim().to_string())
    .filter(|k| !k.is_empty());

    match key {
        Some(k) => (
            StatusCode::OK,
            [(header::CONTENT_TYPE, "text/plain; charset=utf-8")],
            k,
        ),
        None => (
            StatusCode::NOT_FOUND,
            [(header::CONTENT_TYPE, "text/plain; charset=utf-8")],
            String::new(),
        ),
    }
}

/// Start the submission scheduler — checks every 5 minutes for a due global row.
pub fn start_submission_scheduler(db: PgPool, base_domain: String) {
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(300));
        loop {
            interval.tick().await;

            let row = match ensure_global_row(&db).await {
                Ok(r) => r,
                Err(e) => {
                    tracing::warn!("[seo-submit] could not read settings: {}", e);
                    continue;
                }
            };

            if !row.is_enabled {
                continue;
            }
            let due = row.next_run_at.map(|n| n <= Utc::now()).unwrap_or(true);
            if !due {
                continue;
            }

            tracing::info!("[seo-submit] settings due — running submission pass");
            match run_submission(&db, &row, &base_domain).await {
                Ok(v) => tracing::info!(
                    "[seo-submit] pass complete: {} ({} targets)",
                    v["status"],
                    v["targets_submitted"]
                ),
                Err(e) => tracing::warn!("[seo-submit] pass failed: {}", e),
            }
        }
    });
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_locs_dedupes_and_preserves_order() {
        let xml = "<urlset><url><loc>https://a/</loc></url>\
                   <url><loc>https://a/b</loc></url>\
                   <url><loc>https://a/</loc></url></urlset>";
        assert_eq!(parse_locs(xml), vec!["https://a/", "https://a/b"]);
        assert!(parse_locs("<urlset></urlset>").is_empty());
    }

    #[test]
    fn origin_of_extracts_authority() {
        assert_eq!(
            origin_of("https://zaarhub.com/apopka/businesses"),
            Some("https://zaarhub.com".to_string())
        );
        assert_eq!(
            origin_of("http://127.0.0.1:9997/ok"),
            Some("http://127.0.0.1:9997".to_string())
        );
        assert_eq!(origin_of("not-a-url"), None);
    }

    #[test]
    fn no_dead_ping_defaults_are_seeded() {
        // Google (404) and Bing (410) retired ?sitemap= pings; nothing is seeded.
        let v: Value = serde_json::from_str(DEFAULT_TARGETS).unwrap();
        assert_eq!(v.as_array().map(|a| a.len()), Some(0));
    }
}
